server:
  port: 8080

spring:
  application:
    name: country-routing-service

countries:
  json:
    url: https://raw.githubusercontent.com/mledoze/countries/master/countries.json

logging:
  level:
    com.test.routing: INFO
